apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-model-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-model-operator.labels" . | nindent 4 }}
