apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-model-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-model-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  type: ClusterIP
  selector:
    {{- include "ai-model-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  ports:
    - name: https
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: healthz
      port: 8081
      targetPort: 8081
      protocol: TCP
