replicaCount: 1

image:
  repository: ghcr.io/otherjamesbrown/ai-aas/ai-model-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Environment variables for the operator
env: []
