apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-router-service-development
  namespace: argocd
  labels:
    environment: development
    app: api-router-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-development
  source:
    repoURL: https://github.com/otherjamesbrown/ai-aas
    targetRevision: main
    path: services/api-router-service/deployments/helm/api-router-service
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository: ghcr.io/otherjamesbrown/api-router-service
          tag: latest
          pullPolicy: Always
        env:
          - name: ENVIRONMENT
            value: development
          - name: LOG_LEVEL
            value: debug
          - name: HTTP_PORT
            value: "8080"
          - name: SERVICE_NAME
            value: api-router-service
          - name: USER_ORG_SERVICE_URL
            value: "http://user-org-service-development-user-org-service.user-org-service.svc.cluster.local:8081"
          - name: USER_ORG_SERVICE_TIMEOUT
            value: "2s"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "otel-collector.monitoring.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
        service:
          type: ClusterIP
          port: 8080
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/proxy-body-size: "50m"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
          hosts:
            - host: api.dev.ai-aas.local
              paths:
                - path: /
                  pathType: Prefix
          tls: []
        redis:
          address: redis.development.svc.cluster.local:6379
        kafka:
          brokers: ""
          topic: usage.records.v1
          auditTopic: audit.router
        configService:
          endpoint: "etcd-service:2379"
          watchEnabled: true
        backends:
          endpoints: "vllm-gpt-oss-20b:http://vllm-gpt-oss-20b.system.svc.cluster.local:8000/v1/chat/completions"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

