apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-router-service-development
  namespace: argocd
  labels:
    environment: development
    app: api-router-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-development
  source:
    repoURL: https://github.com/otherjamesbrown/ai-aas
    targetRevision: main
    path: services/api-router-service/deployments/helm/api-router-service
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository: ghcr.io/otherjamesbrown/api-router-service
          tag: latest
          pullPolicy: Always
        env:
          - name: ENVIRONMENT
            value: development
          - name: LOG_LEVEL
            value: info
          - name: HTTP_PORT
            value: "8080"
          - name: SERVICE_NAME
            value: api-router-service
        service:
          type: ClusterIP
          port: 8080
        redis:
          address: redis.development.svc.cluster.local:6379
        kafka:
          brokers: ""
          topic: usage.records.v1
          auditTopic: audit.router
        configService:
          endpoint: ""
          watchEnabled: false
        backends:
          endpoints: ""
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

