apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-development
  namespace: argocd
  labels:
    environment: development
    app: kserve
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-development
  source:
    repoURL: https://github.com/kserve/kserve
    targetRevision: v0.11.2
    path: install/v0.11.2
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
