apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-org-service-development
  namespace: argocd
  labels:
    environment: development
    app: user-org-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-development
  source:
    repoURL: https://github.com/otherjamesbrown/ai-aas
    targetRevision: 020-model-management
    path: services/user-org-service/configs/helm
    helm:
      valueFiles:
        - values.yaml
        - values-development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user-org-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

