global:
  image:
    tag: v2.11.0

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.dev.otherjamesbrown.com
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.dev.otherjamesbrown.com

redis:
  auth:
    enabled: false

controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
