// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: preprocessor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents a single chat message in OpenAI format
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // "system", "user", "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Text content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_preprocessor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_preprocessor_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PreprocessRequest contains the chat messages to preprocess
type PreprocessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model_id is the HuggingFace model identifier for tokenizer lookup
	// Example: "meta-llama/Llama-3.1-8B-Instruct", "openai/gpt-oss-20b"
	ModelId string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// engine_type determines output format:
	// - "vllm", "triton_string": returns formatted_prompt only
	// - "triton_tensor": returns input_ids for direct tensor input
	EngineType string `protobuf:"bytes,2,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	// messages is the chat history in OpenAI format
	Messages []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// Optional generation parameters (passed through for tensor mode)
	MaxTokens     int32   `protobuf:"varint,10,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32 `protobuf:"fixed32,11,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          float32 `protobuf:"fixed32,12,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Stream        bool    `protobuf:"varint,13,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreprocessRequest) Reset() {
	*x = PreprocessRequest{}
	mi := &file_preprocessor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprocessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprocessRequest) ProtoMessage() {}

func (x *PreprocessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprocessRequest.ProtoReflect.Descriptor instead.
func (*PreprocessRequest) Descriptor() ([]byte, []int) {
	return file_preprocessor_proto_rawDescGZIP(), []int{1}
}

func (x *PreprocessRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PreprocessRequest) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *PreprocessRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PreprocessRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *PreprocessRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *PreprocessRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *PreprocessRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// PreprocessResponse contains the preprocessed output
type PreprocessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// formatted_prompt is the fully formatted prompt string with chat template applied
	// Used for vLLM and triton_string engine types
	FormattedPrompt string `protobuf:"bytes,1,opt,name=formatted_prompt,json=formattedPrompt,proto3" json:"formatted_prompt,omitempty"`
	// input_ids is the tokenized prompt as int32 array
	// Used for triton_tensor engine type
	InputIds []int32 `protobuf:"varint,2,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`
	// input_shape describes the tensor shape for input_ids (e.g., [1, 256])
	InputShape []int64 `protobuf:"varint,3,rep,packed,name=input_shape,json=inputShape,proto3" json:"input_shape,omitempty"`
	// prompt_token_count is the number of tokens in the prompt
	PromptTokenCount int32 `protobuf:"varint,5,opt,name=prompt_token_count,json=promptTokenCount,proto3" json:"prompt_token_count,omitempty"`
	// error_message contains any error that occurred during preprocessing
	ErrorMessage  string `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreprocessResponse) Reset() {
	*x = PreprocessResponse{}
	mi := &file_preprocessor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprocessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprocessResponse) ProtoMessage() {}

func (x *PreprocessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprocessResponse.ProtoReflect.Descriptor instead.
func (*PreprocessResponse) Descriptor() ([]byte, []int) {
	return file_preprocessor_proto_rawDescGZIP(), []int{2}
}

func (x *PreprocessResponse) GetFormattedPrompt() string {
	if x != nil {
		return x.FormattedPrompt
	}
	return ""
}

func (x *PreprocessResponse) GetInputIds() []int32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *PreprocessResponse) GetInputShape() []int64 {
	if x != nil {
		return x.InputShape
	}
	return nil
}

func (x *PreprocessResponse) GetPromptTokenCount() int32 {
	if x != nil {
		return x.PromptTokenCount
	}
	return 0
}

func (x *PreprocessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_preprocessor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_preprocessor_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready indicates if the service is ready to handle requests
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// message provides additional status information
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// loaded_tokenizers maps model_id to load status (true if cached)
	LoadedTokenizers map[string]bool `protobuf:"bytes,3,rep,name=loaded_tokenizers,json=loadedTokenizers,proto3" json:"loaded_tokenizers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_preprocessor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_preprocessor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_preprocessor_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetLoadedTokenizers() map[string]bool {
	if x != nil {
		return x.LoadedTokenizers
	}
	return nil
}

var File_preprocessor_proto protoreflect.FileDescriptor

const file_preprocessor_proto_rawDesc = "" +
	"\n" +
	"\x12preprocessor.proto\x12\fpreprocessor\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf0\x01\n" +
	"\x11PreprocessRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1f\n" +
	"\vengine_type\x18\x02 \x01(\tR\n" +
	"engineType\x121\n" +
	"\bmessages\x18\x03 \x03(\v2\x15.preprocessor.MessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\n" +
	" \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\v \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\f \x01(\x02R\x04topP\x12\x16\n" +
	"\x06stream\x18\r \x01(\bR\x06stream\"\xd0\x01\n" +
	"\x12PreprocessResponse\x12)\n" +
	"\x10formatted_prompt\x18\x01 \x01(\tR\x0fformattedPrompt\x12\x1b\n" +
	"\tinput_ids\x18\x02 \x03(\x05R\binputIds\x12\x1f\n" +
	"\vinput_shape\x18\x03 \x03(\x03R\n" +
	"inputShape\x12,\n" +
	"\x12prompt_token_count\x18\x05 \x01(\x05R\x10promptTokenCount\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12HealthCheckRequest\"\xf0\x01\n" +
	"\x13HealthCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12d\n" +
	"\x11loaded_tokenizers\x18\x03 \x03(\v27.preprocessor.HealthCheckResponse.LoadedTokenizersEntryR\x10loadedTokenizers\x1aC\n" +
	"\x15LoadedTokenizersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xba\x01\n" +
	"\x13PreprocessorService\x12O\n" +
	"\n" +
	"Preprocess\x12\x1f.preprocessor.PreprocessRequest\x1a .preprocessor.PreprocessResponse\x12R\n" +
	"\vHealthCheck\x12 .preprocessor.HealthCheckRequest\x1a!.preprocessor.HealthCheckResponseB`Z^github.com/otherjamesbrown/ai-aas/services/api-router-service/internal/adapter/preprocessor/pbb\x06proto3"

var (
	file_preprocessor_proto_rawDescOnce sync.Once
	file_preprocessor_proto_rawDescData []byte
)

func file_preprocessor_proto_rawDescGZIP() []byte {
	file_preprocessor_proto_rawDescOnce.Do(func() {
		file_preprocessor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preprocessor_proto_rawDesc), len(file_preprocessor_proto_rawDesc)))
	})
	return file_preprocessor_proto_rawDescData
}

var file_preprocessor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_preprocessor_proto_goTypes = []any{
	(*Message)(nil),             // 0: preprocessor.Message
	(*PreprocessRequest)(nil),   // 1: preprocessor.PreprocessRequest
	(*PreprocessResponse)(nil),  // 2: preprocessor.PreprocessResponse
	(*HealthCheckRequest)(nil),  // 3: preprocessor.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 4: preprocessor.HealthCheckResponse
	nil,                         // 5: preprocessor.HealthCheckResponse.LoadedTokenizersEntry
}
var file_preprocessor_proto_depIdxs = []int32{
	0, // 0: preprocessor.PreprocessRequest.messages:type_name -> preprocessor.Message
	5, // 1: preprocessor.HealthCheckResponse.loaded_tokenizers:type_name -> preprocessor.HealthCheckResponse.LoadedTokenizersEntry
	1, // 2: preprocessor.PreprocessorService.Preprocess:input_type -> preprocessor.PreprocessRequest
	3, // 3: preprocessor.PreprocessorService.HealthCheck:input_type -> preprocessor.HealthCheckRequest
	2, // 4: preprocessor.PreprocessorService.Preprocess:output_type -> preprocessor.PreprocessResponse
	4, // 5: preprocessor.PreprocessorService.HealthCheck:output_type -> preprocessor.HealthCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_preprocessor_proto_init() }
func file_preprocessor_proto_init() {
	if File_preprocessor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preprocessor_proto_rawDesc), len(file_preprocessor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preprocessor_proto_goTypes,
		DependencyIndexes: file_preprocessor_proto_depIdxs,
		MessageInfos:      file_preprocessor_proto_msgTypes,
	}.Build()
	File_preprocessor_proto = out.File
	file_preprocessor_proto_goTypes = nil
	file_preprocessor_proto_depIdxs = nil
}
