apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-development
  namespace: argocd
spec:
  description: Platform infrastructure applications for development
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
