apiVersion: v1
kind: Service
metadata:
  name: {{ include "preprocessor-service.fullname" . }}
  labels:
    {{- include "preprocessor-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "preprocessor-service.selectorLabels" . | nindent 4 }}
